name: appstore
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.8.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow=1.2.3=py310h06a4308_1
  - arrow-cpp=11.0.0=h374c478_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attrs=22.1.0=py310h06a4308_0
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - boltons=23.0.0=py310h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cchardet=2.1.7=py310h6a678d5_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - chardet=4.0.0=py310h06a4308_1003
  - colorama=0.4.6=py310h06a4308_0
  - comm=0.1.2=py310h06a4308_0
  - conda=23.7.1=py310h06a4308_0
  - conda-package-handling=2.1.0=py310h06a4308_0
  - conda-package-streaming=0.8.0=py310h06a4308_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - coverage=7.2.2=py310h5eee18b_0
  - cruft=2.15.0=pypyh1a96a4e_0
  - cryptography=41.0.2=py310h22a60cf_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dependency_injector=4.41.0=py310h1fa729e_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - gitpython=3.1.30=py310h06a4308_0
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h2531618_0
  - greenlet=2.0.1=py310h6a678d5_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=6.0.0=py310h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.19.2=py310h2f386ee_0
  - ipython=8.12.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.1.0=py310h06a4308_0
  - jupyter_core=5.3.0=py310h06a4308_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libclang13=14.0.6=default_he11475f_1
  - libcurl=8.1.1=h251f7ec_1
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.52.0=h2d74bed_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=2.2.0=py310h06a4308_1
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.7.1=py310h06a4308_1
  - matplotlib-base=3.7.1=py310h1128e8f_1
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - multidict=6.0.2=py310h5eee18b_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py310h85018f9_1
  - numpy=1.25.0=py310h5f9d8c6_0
  - numpy-base=1.25.0=py310hb5e798b_0
  - openssl=3.1.1=hd590300_1
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.0=py310h06a4308_0
  - pandas=2.0.3=py310h7cbd5c2_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=0.5.3=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.2.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - ply=3.11=py310h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pyarrow=11.0.0=py310h468efa6_0
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pymysql=1.0.2=py310h06a4308_1
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - pytest=7.3.1=py310h06a4308_0
  - pytest-cov=4.0.0=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-dotenv=0.21.0=py310h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7=py310h06a4308_0
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=25.1.0=py310h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - rich=13.3.5=py310h06a4308_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - scipy=1.10.1=py310h5f9d8c6_1
  - sentry-sdk=1.9.0=py310h06a4308_0
  - setproctitle=1.2.2=py310h7f8727e_0
  - setuptools=68.0.0=py310h06a4308_0
  - shellingham=1.5.0=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.9=h295c915_0
  - sqlalchemy=1.4.39=py310h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.7.1=py310h06a4308_0
  - typer=0.9.0=py310h06a4308_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - utf8proc=2.6.1=h27cfd23_0
  - wandb=0.15.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py310h06a4308_0
  - wordcloud=1.9.2=py310h5eee18b_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py310h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - autoflake==1.7.8
      - black==23.3.0
      - cfgv==3.3.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - distlib==0.3.6
      - d8analysis==0.0.3
      - eradicate==2.3.0
      - exceptiongroup==1.1.1
      - filelock==3.12.2
      - flake8==5.0.4
      - flake8-bugbear==23.3.12
      - flake8-builtins==2.1.0
      - flake8-comprehensions==3.13.0
      - flake8-debugger==4.1.2
      - flake8-logging-format==0.9.0
      - ghp-import==2.1.0
      - gitdb==4.0.10
      - google-play-scraper==1.2.4
      - griffe==0.29.1
      - identify==2.5.24
      - isort==5.12.0
      - logmatic-python==0.1.7
      - markdown==3.3.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mkdocs==1.4.3
      - mkdocs-autorefs==0.4.1
      - mkdocs-material==9.1.17
      - mkdocs-material-extensions==1.1.1
      - mkdocstrings==0.22.0
      - mkdocstrings-python==1.1.2
      - mypy==1.4.1
      - mypy-extensions==1.0.0
      - nodeenv==1.8.0
      - pathspec==0.11.1
      - pep8-naming==0.13.3
      - platformdirs==3.8.0
      - pre-commit==3.3.3
      - pycodestyle==2.9.1
      - pyflakes==2.5.0
      - pymdown-extensions==10.0.1
      - pyqt5-sip==12.11.0
      - pytest-github-actions-annotate-failures==0.2.0
      - python-json-logger==2.0.7
      - python-kacl==0.4.6
      - pyupgrade==3.7.0
      - pyyaml-env-tag==0.1
      - regex==2023.6.3
      - semver==3.0.1
      - tokenize-rt==5.1.0
      - tryceratops==2.1.1
      - typing-extensions==4.6.3
      - urllib3==2.0.3
      - virtualenv==20.23.1
      - watchdog==3.0.0
prefix: /home/john/anaconda3/envs/appstore
