# ================================================================================================ #
#                                 JUPYTERBOOK CONFIG                                               #
# ================================================================================================ #
# Learn more at https://jupyterbook.org/customize/config.html

title: |
  <p style="text-align:left"><span style="color:#002B5B"><span style="font-size:36px"><span style="font-family:Lato">VoCMobile.ai</span></span><span style="font-size:18px"><span style="font-family:Lato">Generative-AI Powered Mobile App Voice of Customer and Analytics</span></span></span></p>

author: John James
copyright: "2023"
logo: "figures/logo.png"
root: index
options:
  numbered: true
only_build_toc_files: true

# ================================================================================================ #
#                                        EXECUTE                                                   #
# ================================================================================================ #
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns: ["*.py"]

# ================================================================================================ #
#                                        LATEX                                                     #
# ================================================================================================ #
latex:
  latex_documents:
    targetname: aimobile.tex

# ================================================================================================ #
#                                       BIBTEX                                                     #
# ================================================================================================ #
bibtex_bibfiles:
  - references.bib
# sphinx:
#   config:
#     bibtex_reference_style: super
# ================================================================================================ #
#                                       HTML                                                       #
# ================================================================================================ #
html:
  favicon: "figures/favicon.png" # A path to a favicon image
  use_multitoc_numbering: true # Whether to continue numbering over multiple TOC sections.
  use_edit_page_button: true # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true # Whether to add a link to your repository button
  use_issues_button: true # Whether to add an "open an issue" button
  extra_navbar: "" # Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer: "" # Will be displayed underneath the footer.
  google_analytics_id: "" # A GA id that can be used to track book views.
  home_page_in_navbar: true # Whether to include your home page in the left Navigation Bar

# ================================================================================================ #
#                                  LAUNCH BUTTONS                                                  #
# ================================================================================================ #
launch_buttons:
  notebook_interface: classic # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: "" # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe: false # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url: "https://colab.research.google.com" # The URL of Google Colab

# ================================================================================================ #
#                                    REPOSITORY                                                    #
# ================================================================================================ #
repository:
  url: https://github.com/john-james-ai/aimobile # Online location of your book
  path_to_book: jbook # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# ================================================================================================ #
#                                  SPHINX EXTRAS                                                   #
# ================================================================================================ #
shinx:
  extra_extensions:
    - sphinx_click.ext
    - sphinx_inline_tabs
    - sphinx_tabs.tabs
    - sphinx_panels
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    intersphinx_mapping:
      Python 3: ["https://docs.python.org/3/", null]
      tensorflow:
        [
          "https://www.tensorflow.org/api_docs/python",
          "https://github.com/mr-ubik/tensorflow-intersphinx/raw/master/tf2_py_objects.inv",
        ]
      matplotlib [stable]: ["https://matplotlib.org/stable/", null]
      numpy [stable]: ["https://numpy.org/doc/stable/", null]
      pandas [latest?]: ["https://pandas.pydata.org/docs/", null]
      scikit-learn [stable]: ["https://scikit-learn.org/stable/", null]
      scipy [latest]: ["https://docs.scipy.org/doc/scipy/reference/", null]
      jax [latest]: ["https://jax.readthedocs.io/en/latest/", null]
      seaborn [stable]: ["https://seaborn.pydata.org/", null]
      exmol [latest]: ["https://ur-whitelab.github.io/exmol/", null]
# ================================================================================================ #
#                                     PARSING                                                      #
# ================================================================================================ #
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution