#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AI-Enabled Voice of the Mobile Technology Customer                                  #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.10                                                                             #
# Filename   : /config/logging.yml                                                                 #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/aimobile                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Friday May 19th 2023 11:37:01 pm                                                    #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING CONFIG                                               #
# ------------------------------------------------------------------------------------------------ #
logging:
  version: 1
  formatters:
    console:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
      datefmt: "%m/%d/%Y %I:%M:%S %p"
    file:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s] : %(message)s"
      datefmt: "%m/%d/%Y %I:%M:%S %p"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "INFO"
      formatter: "console"
      stream: "ext://sys.stderr"
    file:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: file
      when: midnight
      interval: 1
      backupCount: 0
      level: "DEBUG"
      filename: logs/aimobile.log
  root:
    level: "DEBUG"
    handlers: ["console", "file"]
  disable_existing_loggers: False